<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <form method="post" action="controllers/user-form.php">
        <fieldset>
            <label for="email">
                Email
            </label>
            <input type="email" id="email" name="email" />
        </fieldset>
        <fieldset>
            <label for="password">
                Mot de passe
            </label>
            <input type="password" id="password" name="password" />
        </fieldset>
        <fieldset>
            <label for="confirmPassword">
                Confirmation mot de passe
            </label>
            <input type="password" id="confirmPassword" name="confirmPassword" />
        </fieldset>
        <fieldset>
            <label for="newsletter">
                Inscription à la newsletter
            </label>
            <input type="checkbox" id="newsletter" name="newsletter" value="newsletter"/>
        </fieldset>
        <fieldset>
            <button type="submit">Envoyer</button>
        </fieldset>
    </form>
</main>

